apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-20"
spec:
  provider: aws
  secretObjects:
    - secretName: k8s-secret
      type: Opaque
      data:
        - objectName: secretKey1
          key: TEST
        - objectName: secretKey2
          key: SERBAN
        - objectName: secretKey3
          key: SERBYX
        - objectName: secretKey4
          key: DATABASE_URL
  parameters:
    objects: |
      - objectName: {{ .Values.secretsManagerKey }}
        objectType: secretsmanager
        jmesPath:
          - path: TEST
            objectAlias: secretKey1 
          - path: SERBAN 
            objectAlias: secretKey2
          - path: SERBYX
            objectAlias: secretKey3
          - path: DATABASE_URL
            objectAlias: secretKey4