apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-access-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::140209482387:role/EksClusterGetSecretsRole"
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"