apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name}}
  ports:
  - protocol: TCP
    port: {{ .Values.svcPort }}
    targetPort: {{ .Values.containerPort }}
  type: NodePort